### ISSUE TITLE
Help with bridging swift to objc

### ISSUE THREAD

**Issue by MohammedBashiru** [macinsmith/SwiftObjcEnumExample#1]
In swift I have 
`public enum PaymentMethods: String {
    case card = "CARD", account = "ACCOUNT", paypal = "PAYPAL"
}
`

Which is used in a class as 

`public class SomeClassName {
   var supportedPaymentMethods:[PaymentMethods]!
}
`

how do I bridge or expose both the enum and the **supportedPaymentMethods** to objc.
Would love to hear from you.

**Comment by macinsmith** [comment]
Sorry, I just saw your email.  It got put in my spam folder.

Remember that Obj C only has integer values for enums.  You will have to create a mapping function that maps the string to the ObjC enum. 

Hope this helps.

Steve

On Dec 15, 2019, at 4:06 PM, Mohammed Bashiru <notifications@github.com <mailto:notifications@github.com>> wrote:

In swift I have
public enum PaymentMethods: String { case card = "CARD", account = "ACCOUNT", paypal = "PAYPAL" }

Which is used in a class as

public class SomeClassName { var supportedPaymentMethods:[PaymentMethods]! }

how do I bridge or expose both the enum and the supportedPaymentMethods to objc.
Would love to hear from you.

**Comment by MohammedBashiru** [comment]
@macinsmith Hello thanks for your reply.

Could you give me a slight example of what you mean. Am pretty much new to Objc & Swift and does not fully understand its concepts.

Thanks

**Comment by macinsmith** [comment]
Drop this in a playground and you can see it work.

public enum PaymentMethods: String {
    case card = "CARD"
    case account = "ACCOUNT"
    case paypal = "PAYPAL"
    
}

func PaymentMethodString(pmtMethod: PaymentMethods) -> NSString {
    return NSString(string: pmtMethod.rawValue)
}

print("card = \(PaymentMethodString(pmtMethod: .card))")
print("account = \(PaymentMethodString(pmtMethod: .account))")
print("paypal = \(PaymentMethodString(pmtMethod: .paypal))")

Steve


On Dec 17, 2019, at 9:43 AM, Mohammed Bashiru <notifications@github.com> wrote:

@macinsmith <https://github.com/macinsmith> Hello thanks for your reply.

Could you give me a slight example of what you mean. Am pretty much new to Objc & Swift and does not fully understand its concepts.

Thanks

**Comment by MohammedBashiru** [comment]
Hello @macinsmith yes your example above works but I still don't know how to set it as a type of a variable. As in my original question. 

`public class SomeClassName { 
    var supportedPaymentMethods: [PaymentMethods]! 
}`

you can see **supportedPaymentMethods** is  of type Array of type PaymentMethods. 
This is the part that confuses me. I need to be able to access this property in Objc.

and since the String Enums not supported in Objc. I don't know how to change the type of **supportedPaymentMethods** so it becomes accessible.

I tried this
`
@objc(supportedPaymentMethods)
public var objc_supportedPaymentMethods: [Int]!
`

but since I set the type here as an Int property is accessible in Objc but variable assigned to it is not valid as the original swift code wants an Enum of type **PaymentMethods**

I hope you understand me.

**Comment by macinsmith** [comment]
In ObjC you can create an array of NSString by referencing all the types in the enum. Then you can use that NSString in ObjC to look up the payment type to see if it is in the array.

I suggest that you check out https://www.appcoda.com <https://www.appcoda.com/>.  They have whole books on beginning Swift and Objective C.  Also RayWinderlich.com <http://raywinderlich.com/> is a good place to go

Steve

On Dec 17, 2019, at 1:35 PM, Mohammed Bashiru <notifications@github.com> wrote:

Hello @macinsmith <https://github.com/macinsmith> yes your example above works but I still don't know how to set it as a type of a variable. As in my original question.

public class SomeClassName { var supportedPaymentMethods: [PaymentMethods]! }

you can see supportedPaymentMethods is of type Array of type PaymentMethods.
This is the part that confuses me. I need to be able to access this property in Objc.

and since the String Enums not supported in Objc. I don't know how to change the type of supportedPaymentMethods so it becomes accessible.

I tried this
@objc(supportedPaymentMethods) public var objc_supportedPaymentMethods: [Int]!

but since I set the type here as an Int property is accessible in Objc but variable assigned to it is not valid as the original swift code wants an Enum of type PaymentMethods

I hope you understand me.

**Comment by MohammedBashiru** [comment]
Thanks @macinsmith  I got it to work. I ended created a temporal Array of NSStrings and looping over these strings in swift to generate the enums.
